CREATE TABLE IF NOT EXISTS "gm"."reservations_Main" (
"rsvno" VARCHAR(8) NOT NULL,
"contact" VARCHAR(8) NOT NULL,
"status" VARCHAR(2) DEFAULT 'A' NOT NULL,
"cr8date" DATE NULL,
"cr8time" TIME WITHOUT TIME ZONE NULL,
"cr8user" VARCHAR(8) NULL,
"lastdate" DATE NULL,
"lasttime" TIME WITHOUT TIME ZONE NULL,
"lastuser" VARCHAR(8) NULL,
"arrdate" DATE NULL,
"depdate" DATE NULL,
"grpsize" INT DEFAULT '1' NOT NULL,
"grpsizex" INT DEFAULT '0' NOT NULL,
"client" VARCHAR(40) NULL,
"owner" VARCHAR(30) NULL,
"area" VARCHAR(2) NOT NULL,
"company" VARCHAR(1) NOT NULL,
"allowfup" BOOLEAN DEFAULT 'true',
"firm" BOOLEAN DEFAULT 'true',
"system" VARCHAR(2) DEFAULT 'R' NOT NULL,
"cidate" DATE NULL,
"citime" TIME WITHOUT TIME ZONE NULL,
"ciuser" VARCHAR(8) NULL,
"codate" DATE NULL,
"cotime" TIME WITHOUT TIME ZONE NULL,
"couser" VARCHAR(8) NULL,
"agent" INT NULL,
"commrate" NUMERIC(5,2) DEFAULT '0.00' NULL,
"taxable" BOOLEAN DEFAULT 'true',
"taxno" VARCHAR(20) NULL,
"pmtterms" VARCHAR(8) NULL,
"pmttermsx" VARCHAR(8) NULL,
"lockamts" BOOLEAN DEFAULT 'false',
"lockdates" BOOLEAN DEFAULT 'false',
"pmtdate1" DATE NULL,
"pmtamt1" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtapp1" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtrem1" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtbal1" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtdate2" DATE NULL,
"pmtamt2" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtapp2" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtrem2" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtbal2" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtdate3" DATE NULL,
"pmtamt3" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtapp3" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtrem3" NUMERIC(10,2) DEFAULT '0.00' NULL,
"pmtbal3" NUMERIC(10,2) DEFAULT '0.00' NULL,
"charges" NUMERIC(10,2) DEFAULT '0.00' NULL,
"comped" NUMERIC(10,2) DEFAULT '0.00' NULL,
"discount" NUMERIC(10,2) DEFAULT '0.00' NULL,
"tip" NUMERIC(10,2) DEFAULT '0.00' NULL,
"comm" NUMERIC(10,2) DEFAULT '0.00' NULL,
"comm3" NUMERIC(10,2) DEFAULT '0.00' NULL,
"sales" NUMERIC(10,2) DEFAULT '0.00' NULL,
"taxes" NUMERIC(10,2) DEFAULT '0.00' NULL,
"total" NUMERIC(10,2) DEFAULT '0.00' NULL,
"cancdate" DATE NULL,
"cancwho" VARCHAR(40) NULL,
"cancreas" VARCHAR(8) NULL,
"cancfee" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xcharges" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xcomped" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xdiscount" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xtip" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xcomm" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xcomm3" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xsales" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xtaxes" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xtotal" NUMERIC(10,2) DEFAULT '0.00' NULL,
"xtaxdtls" JSONB,
"reseller" VARCHAR(8) NULL,
"rslrrsvno" VARCHAR(8) NOT NULL,
PRIMARY KEY("rsvno")
);
CREATE TABLE IF NOT EXISTS "gm"."reservations_Maintaxes" (
"rsvno" VARCHAR(8) NOT NULL,
"taxcode" VARCHAR(8) NOT NULL,
"amount" NUMERIC(10,2) DEFAULT '0.00' NULL,
PRIMARY KEY("rsvno","taxcode")
);
CREATE TABLE IF NOT EXISTS "gm"."reservations_Maingls" (
"rsvno" VARCHAR(8) NOT NULL,
"glcode" VARCHAR(8) NOT NULL,
"amount" NUMERIC(10,2) DEFAULT '0.00' NULL,
PRIMARY KEY("rsvno","glcode")
);
ALTER TABLE "gm"."reservations_Main"
 ADD CONSTRAINT "reservations_main_contact_fkey" FOREIGN KEY("contact") REFERENCES "gm"."contacts_Contact" ("id") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_agent_fkey" FOREIGN KEY("agent") REFERENCES "gm"."contacts_Contact" ("id") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_area_fkey" FOREIGN KEY("area") REFERENCES "gm"."items_Area" ("code") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_company_fkey" FOREIGN KEY("company") REFERENCES "gm"."contacts_Company" ("id") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_pmtterms_fkey" FOREIGN KEY("pmtterms") REFERENCES "gm"."items_Pmtterms" ("code") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_pmttermsx_fkey" FOREIGN KEY("pmttermsx") REFERENCES "gm"."items_Pmtterms" ("code") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_cancreas_fkey" FOREIGN KEY("cancreas") REFERENCES "gm"."reservations_Cancreas" ("code") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_main_reseller_fkey" FOREIGN KEY("reseller") REFERENCES "gm"."items_Reseller" ("code") ON DELETE NO ACTION; CREATE INDEX "reservations_main_contact_index" ON "gm"."reservations_Main" (contact); CREATE INDEX "reservations_main_agent_index" ON "gm"."reservations_Main" (agent); CREATE INDEX "reservations_main_arrdate_index" ON "gm"."reservations_Main" (arrdate); CREATE INDEX "reservations_main_depdate_index" ON "gm"."reservations_Main" (depdate)
ALTER TABLE "gm"."reservations_Maintaxes"
 ADD CONSTRAINT "reservations_maintaxes_rsvno_fkey" FOREIGN KEY("rsvno") REFERENCES "gm"."reservations_Main" ("rsvno") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_maintaxes_tax_fkey" FOREIGN KEY("taxcode") REFERENCES "gm"."items_Tax" ("code") ON DELETE NO ACTION; CREATE INDEX "reservations_maintaxes_rsvno_index" ON "gm"."reservations_Maintaxes" (rsvno); CREATE INDEX "reservations_maintaxes_tax_index" ON "gm"."reservations_Maintaxes" (taxcode)
ALTER TABLE "gm"."reservations_Maingls"
 ADD CONSTRAINT "reservations_maingls_rsvno_fkey" FOREIGN KEY("rsvno") REFERENCES "gm"."reservations_Main" ("rsvno") ON DELETE NO ACTION,
 ADD CONSTRAINT "reservations_maingls_gl_fkey" FOREIGN KEY("glcode") REFERENCES "gm"."items_Glcode" ("code") ON DELETE NO ACTION; CREATE INDEX "reservations_maingls_rsvno_index" ON "gm"."reservations_Maingls" (rsvno); CREATE INDEX "reservations_maingls_gl_index" ON "gm"."reservations_Maingls" (glcode)
